/*
# Create categories and products tables for Eyara Store

## Summary
Creates two tables — `categories` and `products` — to store the store's catalog
in Supabase instead of fetching from the dummyjson API. This enables a hidden
admin panel at /admin to create, read, update, and delete both categories and
products (including prices, images, descriptions, stock, tags, etc.).

## 1. New Tables

### categories
- `id` (uuid, primary key)
- `name` (text, not null) — display name, e.g. "Men's Shirts"
- `slug` (text, not null, unique) — URL-friendly identifier
- `description` (text, nullable) — optional category description
- `image_url` (text, nullable) — optional category image
- `demographic` (text, not null) — 'men', 'women', or 'kids'
- `product_type` (text, not null) — 'clothes' or 'shoes'
- `sort_order` (integer, default 0) — manual ordering
- `created_at` (timestamptz, default now())

### products
- `id` (uuid, primary key)
- `name` (text, not null)
- `slug` (text, not null, unique) — URL-friendly identifier
- `description` (text, nullable)
- `price` (integer, not null) — in KES
- `compare_at_price` (integer, nullable) — original price for discount display
- `image_url` (text, nullable) — primary image
- `gallery` (text[], default '{}') — additional images
- `category_id` (uuid, nullable, FK to categories.id ON DELETE SET NULL)
- `demographic` (text, not null) — 'men', 'women', or 'kids'
- `product_type` (text, not null) — 'clothes' or 'shoes'
- `rating` (numeric, default 0) — 0 to 5
- `review_count` (integer, default 0)
- `featured` (boolean, default false)
- `in_stock` (boolean, default true)
- `tags` (text[], default '{}')
- `created_at` (timestamptz, default now())
- `updated_at` (timestamptz, default now())

## 2. Indexes
- `products_category_id_idx` on products.category_id
- `products_demographic_idx` on products.demographic
- `products_product_type_idx` on products.product_type
- `products_featured_idx` on products.featured
- `categories_slug_idx` on categories.slug

## 3. Security
- RLS enabled on both tables.
- This is a single-tenant store with no sign-in on the customer-facing site.
  The admin panel is protected by a client-side password gate (not Supabase Auth),
  so the anon-key client must be able to perform CRUD. Policies allow
  anon + authenticated full CRUD on both tables (the data is intentionally
  shared/store-owned, not per-user).
- `updated_at` auto-updated via trigger on products.

## 4. Important Notes
1. Both tables use `TO anon, authenticated` because the storefront has no login
   and the admin panel uses a simple password gate, not Supabase Auth sessions.
2. The products trigger keeps `updated_at` in sync without app code.
3. UUIDs are generated by the database via `gen_random_uuid()`.
*/

-- Categories table
CREATE TABLE IF NOT EXISTS categories (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  image_url text,
  demographic text NOT NULL DEFAULT 'women',
  product_type text NOT NULL DEFAULT 'clothes',
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Products table
CREATE TABLE IF NOT EXISTS products (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  price integer NOT NULL DEFAULT 0,
  compare_at_price integer,
  image_url text,
  gallery text[] NOT NULL DEFAULT '{}',
  category_id uuid REFERENCES categories(id) ON DELETE SET NULL,
  demographic text NOT NULL DEFAULT 'women',
  product_type text NOT NULL DEFAULT 'clothes',
  rating numeric(2,1) NOT NULL DEFAULT 0,
  review_count integer NOT NULL DEFAULT 0,
  featured boolean NOT NULL DEFAULT false,
  in_stock boolean NOT NULL DEFAULT true,
  tags text[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS products_category_id_idx ON products(category_id);
CREATE INDEX IF NOT EXISTS products_demographic_idx ON products(demographic);
CREATE INDEX IF NOT EXISTS products_product_type_idx ON products(product_type);
CREATE INDEX IF NOT EXISTS products_featured_idx ON products(featured);
CREATE INDEX IF NOT EXISTS categories_slug_idx ON categories(slug);

-- Enable RLS
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- Categories policies (anon + authenticated full CRUD)
DROP POLICY IF EXISTS "anon_select_categories" ON categories;
CREATE POLICY "anon_select_categories" ON categories FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_categories" ON categories;
CREATE POLICY "anon_insert_categories" ON categories FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_categories" ON categories;
CREATE POLICY "anon_update_categories" ON categories FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_categories" ON categories;
CREATE POLICY "anon_delete_categories" ON categories FOR DELETE
  TO anon, authenticated USING (true);

-- Products policies (anon + authenticated full CRUD)
DROP POLICY IF EXISTS "anon_select_products" ON products;
CREATE POLICY "anon_select_products" ON products FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_products" ON products;
CREATE POLICY "anon_insert_products" ON products FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_products" ON products;
CREATE POLICY "anon_update_products" ON products FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_products" ON products;
CREATE POLICY "anon_delete_products" ON products FOR DELETE
  TO anon, authenticated USING (true);

-- Auto-update updated_at trigger for products
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS products_updated_at ON products;
CREATE TRIGGER products_updated_at
  BEFORE UPDATE ON products
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
