/*
# Add more clothing products for each demographic

1. New Products
- Add 10+ additional clothing items for Men
- Add 10+ additional clothing items for Women  
- Add 10+ additional clothing items for Kids

2. Product Categories Added
Men: Polo shirts, jackets, jeans, shorts, hoodies, vests, cardigans
Women: Skirts, blazers, jackets, jumpsuits, coats, cardigans, tunics
Kids: Shorts, t-shirts, jackets, leggings, rompers, sweaters

3. Notes
- All products have realistic KES pricing
- Products include gallery images, tags, and descriptions
- Mix of featured and regular products
- Various price points from budget to premium
- All product images sourced from DummyJSON (https://dummyjson.com)
*/

-- Men's Additional Clothes
INSERT INTO products (name, slug, description, price, compare_at_price, image_url, gallery, category_id, demographic, product_type, rating, review_count, featured, in_stock, tags) VALUES
('Premium Polo Shirt', 'premium-polo-shirt', 'Classic polo shirt in breathable pique cotton. Perfect for smart casual occasions.', 3800, NULL, 'https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/2.webp', '["https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/1.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/3.webp"]', (SELECT id FROM categories WHERE slug = 'men'), 'men', 'clothes', 4.6, 89, false, true, '["polo", "casual", "cotton"]'),
('Denim Jean Jacket', 'denim-jean-jacket', 'Timeless denim jacket with classic styling. A versatile layering piece for all seasons.', 9500, 12000, 'https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/2.webp', '["https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/1.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/3.webp"]', (SELECT id FROM categories WHERE slug = 'men'), 'men', 'clothes', 4.8, 156, true, true, '["jacket", "denim", "casual"]'),
('Comfort Fit Jeans', 'comfort-fit-jeans', 'Relaxed fit jeans with stretch denim for all-day comfort. Classic 5-pocket styling.', 5500, NULL, 'https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/2.webp', '["https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/1.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/3.webp"]', (SELECT id FROM categories WHERE slug = 'men'), 'men', 'clothes', 4.5, 234, false, true, '["jeans", "denim", "casual"]'),
('Summer Cargo Shorts', 'summer-cargo-shorts', 'Lightweight cotton cargo shorts with multiple pockets. Perfect for outdoor adventures.', 3200, NULL, 'https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/2.webp', '["https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/1.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/3.webp"]', (SELECT id FROM categories WHERE slug = 'men'), 'men', 'clothes', 4.4, 78, false, true, '["shorts", "summer", "cargo"]'),
('Fleece Hoodie', 'fleece-hoodie', 'Cozy fleece hoodie with kangaroo pocket. Great for lounging and casual wear.', 4800, NULL, 'https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/2.webp', '["https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/1.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/3.webp"]', (SELECT id FROM categories WHERE slug = 'men'), 'men', 'clothes', 4.7, 189, false, true, '["hoodie", "fleece", "casual"]'),
('Leather Bomber Jacket', 'leather-bomber-jacket', 'Classic leather bomber jacket with ribbed cuffs and hem. Timeless masculine style.', 18000, 22000, 'https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/3.webp', '["https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/1.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/4.webp"]', (SELECT id FROM categories WHERE slug = 'men'), 'men', 'clothes', 4.9, 67, true, true, '["jacket", "leather", "bomber"]'),
('Cotton Henley Shirt', 'cotton-henley-shirt', 'Casual henley shirt with button placket. A versatile essential for everyday wear.', 3500, NULL, 'https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/3.webp', '["https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/1.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/4.webp"]', (SELECT id FROM categories WHERE slug = 'men'), 'men', 'clothes', 4.5, 145, false, true, '["henley", "casual", "cotton"]'),
('Quilted Vest', 'quilted-vest', 'Lightweight quilted vest perfect for layering. Adds warmth without bulk.', 6800, NULL, 'https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/3.webp', '["https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/1.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/4.webp"]', (SELECT id FROM categories WHERE slug = 'men'), 'men', 'clothes', 4.6, 92, false, true, '["vest", "quilted", "layering"]'),
('Linen Beach Pants', 'linen-beach-pants', 'Relaxed linen pants ideal for beach vacations and summer days. Breathable and comfortable.', 5200, NULL, 'https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/3.webp', '["https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/1.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/4.webp"]', (SELECT id FROM categories WHERE slug = 'men'), 'men', 'clothes', 4.7, 56, false, true, '["pants", "linen", "summer"]'),
('Formal Dress Shirt', 'formal-dress-shirt', 'Crispy white dress shirt for formal occasions. French cuff with removable stays.', 5800, NULL, 'https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/3.webp', '["https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/1.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/4.webp"]', (SELECT id FROM categories WHERE slug = 'men'), 'men', 'clothes', 4.8, 203, false, true, '["formal", "dress-shirt", "white"]'),
('Athletic Track Pants', 'athletic-track-pants', 'Comfortable track pants with side stripes. Perfect for workouts or casual wear.', 4200, NULL, 'https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/4.webp', '["https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/1.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/2.webp"]', (SELECT id FROM categories WHERE slug = 'men'), 'men', 'clothes', 4.4, 167, false, true, '["track", "athletic", "sports"]'),
('Thermal Base Layer', 'thermal-base-layer', 'Warm thermal base layer for cold weather. Moisture-wicking fabric keeps you dry.', 3500, NULL, 'https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/4.webp', '["https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/1.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/2.webp"]', (SELECT id FROM categories WHERE slug = 'men'), 'men', 'clothes', 4.6, 112, false, true, '["thermal", "base-layer", "winter"]');

-- Women's Additional Clothes
INSERT INTO products (name, slug, description, price, compare_at_price, image_url, gallery, category_id, demographic, product_type, rating, review_count, featured, in_stock, tags) VALUES
('Pleated Midi Skirt', 'pleated-midi-skirt', 'Elegant pleated midi skirt with elastic waistband. Flattering silhouette for any occasion.', 4500, NULL, 'https://cdn.dummyjson.com/product-images/tops/blue-frock/1.webp', '["https://cdn.dummyjson.com/product-images/tops/blue-frock/2.webp", "https://cdn.dummyjson.com/product-images/tops/blue-frock/3.webp"]', (SELECT id FROM categories WHERE slug = 'women'), 'women', 'clothes', 4.7, 134, false, true, '["skirt", "pleated", "midi"]'),
('Structured Blazer', 'structured-blazer', 'Tailored blazer with sharp shoulders and nipped waist. Polished office-to-evening style.', 11000, 13500, 'https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/1.webp', '["https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/2.webp", "https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/3.webp"]', (SELECT id FROM categories WHERE slug = 'women'), 'women', 'clothes', 4.8, 189, true, true, '["blazer", "formal", "structured"]'),
('Wool Trench Coat', 'wool-trench-coat', 'Classic wool trench coat with belted waist. Timeless outerwear for cooler months.', 16000, NULL, 'https://cdn.dummyjson.com/product-images/tops/gray-dress/1.webp', '["https://cdn.dummyjson.com/product-images/tops/gray-dress/2.webp", "https://cdn.dummyjson.com/product-images/tops/gray-dress/3.webp"]', (SELECT id FROM categories WHERE slug = 'women'), 'women', 'clothes', 4.9, 78, false, true, '["coat", "trench", "wool"]'),
('Silk Jumpsuit', 'silk-jumpsuit', 'Sleek silk jumpsuit with front tie detail. Effortlessly chic for evening events.', 14500, 17000, 'https://cdn.dummyjson.com/product-images/tops/short-frock/1.webp', '["https://cdn.dummyjson.com/product-images/tops/short-frock/2.webp", "https://cdn.dummyjson.com/product-images/tops/short-frock/3.webp"]', (SELECT id FROM categories WHERE slug = 'women'), 'women', 'clothes', 4.8, 56, true, true, '["jumpsuit", "silk", "evening"]'),
('Cotton Wrap Blouse', 'cotton-wrap-blouse', 'Flattering wrap blouse in soft cotton. Adjustable tie waist for perfect fit.', 3800, NULL, 'https://cdn.dummyjson.com/product-images/tops/tartan-dress/1.webp', '["https://cdn.dummyjson.com/product-images/tops/tartan-dress/2.webp", "https://cdn.dummyjson.com/product-images/tops/tartan-dress/3.webp"]', (SELECT id FROM categories WHERE slug = 'women'), 'women', 'clothes', 4.6, 178, false, true, '["blouse", "wrap", "cotton"]'),
('High-Waist Skinny Jeans', 'high-waist-skinny-jeans', 'Figure-flattering high-waist skinny jeans with stretch denim. Modern classic fit.', 6500, NULL, 'https://cdn.dummyjson.com/product-images/womens-dresses/black-women%27s-gown/2.webp', '["https://cdn.dummyjson.com/product-images/womens-dresses/black-women%27s-gown/1.webp", "https://cdn.dummyjson.com/product-images/womens-dresses/black-women%27s-gown/3.webp"]', (SELECT id FROM categories WHERE slug = 'women'), 'women', 'clothes', 4.5, 312, false, true, '["jeans", "skinny", "high-waist"]'),
('Crochet Beach Cover-Up', 'crochet-beach-cover-up', 'Hand-crocheted beach cover-up with intricate patterns. Perfect for pool or beach days.', 5500, NULL, 'https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/2.webp', '["https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/1.webp", "https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/3.webp"]', (SELECT id FROM categories WHERE slug = 'women'), 'women', 'clothes', 4.7, 89, false, true, '["coverup", "crochet", "beach"]'),
('Oversized Knit Sweater', 'oversized-knit-sweater', 'Cozy oversized knit sweater in chunky yarn. Perfect for layering in cooler weather.', 7200, NULL, 'https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/2.webp', '["https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/1.webp", "https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/3.webp"]', (SELECT id FROM categories WHERE slug = 'women'), 'women', 'clothes', 4.8, 156, false, true, '["sweater", "knit", "oversized"]'),
('Tailored Shorts', 'tailored-shorts', 'Smart tailored shorts with pleated front. Dressy enough for work in warm weather.', 4200, NULL, 'https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/2.webp', '["https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/1.webp", "https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/3.webp"]', (SELECT id FROM categories WHERE slug = 'women'), 'women', 'clothes', 4.5, 123, false, true, '["shorts", "tailored", "summer"]'),
('Bohemian Maxi Dress', 'bohemian-maxi-dress', 'Flowing bohemian maxi dress with floral embroidery. Romantic and free-spirited.', 8900, NULL, 'https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/2.webp', '["https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/1.webp", "https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/3.webp"]', (SELECT id FROM categories WHERE slug = 'women'), 'women', 'clothes', 4.7, 98, false, true, '["dress", "maxi", "bohemian"]'),
('Cardigan Coat', 'cardigan-coat', 'Long line cardigan coat with belt. Versatile layering piece for transitional weather.', 8500, NULL, 'https://cdn.dummyjson.com/product-images/womens-dresses/black-women%27s-gown/3.webp', '["https://cdn.dummyjson.com/product-images/womens-dresses/black-women%27s-gown/1.webp", "https://cdn.dummyjson.com/product-images/womens-dresses/black-women%27s-gown/4.webp"]', (SELECT id FROM categories WHERE slug = 'women'), 'women', 'clothes', 4.6, 145, false, true, '["cardigan", "coat", "layering"]'),
('Athletic Leggings', 'athletic-leggings', 'High-performance athletic leggings with moisture-wicking fabric. Four-way stretch.', 4800, NULL, 'https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/3.webp', '["https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/1.webp", "https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/4.webp"]', (SELECT id FROM categories WHERE slug = 'women'), 'women', 'clothes', 4.7, 267, false, true, '["leggings", "athletic", "sports"]'),
('Silk Camisole Top', 'silk-camisole-top', 'Delicate silk camisole with lace trim. Beautiful for layering or solo wear.', 3200, NULL, 'https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/3.webp', '["https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/1.webp", "https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/4.webp"]', (SELECT id FROM categories WHERE slug = 'women'), 'women', 'clothes', 4.5, 112, false, true, '["camisole", "silk", "lace"]'),
('Peasant Blouse', 'peasant-blouse', 'Romantic peasant blouse with embroidery details. Easy fit for effortless style.', 4500, NULL, 'https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/3.webp', '["https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/1.webp", "https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/4.webp"]', (SELECT id FROM categories WHERE slug = 'women'), 'women', 'clothes', 4.6, 89, false, true, '["blouse", "peasant", "embroidery"]');

-- Kids' Additional Clothes  
INSERT INTO products (name, slug, description, price, compare_at_price, image_url, gallery, category_id, demographic, product_type, rating, review_count, featured, in_stock, tags) VALUES
('Classic School Uniform', 'classic-school-uniform', 'Complete school uniform set. Durable fabric designed to withstand daily wear.', 4500, NULL, 'https://cdn.dummyjson.com/product-images/tops/blue-frock/3.webp', '["https://cdn.dummyjson.com/product-images/tops/blue-frock/1.webp", "https://cdn.dummyjson.com/product-images/tops/blue-frock/4.webp"]', (SELECT id FROM categories WHERE slug = 'kids'), 'kids', 'clothes', 4.8, 234, false, true, '["school", "uniform", "boys"]'),
('Rainbow Print T-Shirt', 'rainbow-print-tshirt', 'Fun rainbow print t-shirt in soft cotton. Kids will love the vibrant colors.', 1800, NULL, 'https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/3.webp', '["https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/1.webp", "https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/4.webp"]', (SELECT id FROM categories WHERE slug = 'kids'), 'kids', 'clothes', 4.7, 156, false, true, '["tshirt", "rainbow", "print"]'),
('Cozy Fleece Jacket', 'cozy-fleece-jacket', 'Warm fleece jacket with fun animal pattern. Perfect for cool days at school or play.', 3800, NULL, 'https://cdn.dummyjson.com/product-images/tops/gray-dress/3.webp', '["https://cdn.dummyjson.com/product-images/tops/gray-dress/1.webp", "https://cdn.dummyjson.com/product-images/tops/gray-dress/4.webp"]', (SELECT id FROM categories WHERE slug = 'kids'), 'kids', 'clothes', 4.9, 189, true, true, '["jacket", "fleece", "warm"]'),
('Stretchy Leggings', 'stretchy-leggings', 'Comfortable stretchy leggings with colorful prints. Easy pull-on style for kids.', 2200, NULL, 'https://cdn.dummyjson.com/product-images/tops/short-frock/3.webp', '["https://cdn.dummyjson.com/product-images/tops/short-frock/1.webp", "https://cdn.dummyjson.com/product-images/tops/short-frock/4.webp"]', (SELECT id FROM categories WHERE slug = 'kids'), 'kids', 'clothes', 4.6, 278, false, true, '["leggings", "stretchy", "girls"]'),
('Denim Overalls', 'denim-overalls', 'Classic denim overalls with adjustable straps. Durable for all childhood adventures.', 4200, NULL, 'https://cdn.dummyjson.com/product-images/tops/tartan-dress/3.webp', '["https://cdn.dummyjson.com/product-images/tops/tartan-dress/1.webp", "https://cdn.dummyjson.com/product-images/tops/tartan-dress/4.webp"]', (SELECT id FROM categories WHERE slug = 'kids'), 'kids', 'clothes', 4.8, 145, false, true, '["overalls", "denim", "casual"]'),
('Princess Tutu Dress', 'princess-tutu-dress', 'Magical tutu dress perfect for dress-up or parties. Multiple layers of soft tulle.', 3500, NULL, 'https://cdn.dummyjson.com/product-images/tops/blue-frock/4.webp', '["https://cdn.dummyjson.com/product-images/tops/blue-frock/1.webp", "https://cdn.dummyjson.com/product-images/tops/blue-frock/2.webp"]', (SELECT id FROM categories WHERE slug = 'kids'), 'kids', 'clothes', 4.9, 312, true, true, '["dress", "tutu", "princess"]'),
('Casual Sweatpants', 'casual-sweatpants', 'Soft cotton sweatpants with elastic waistband. Perfect for lounging and play time.', 2500, NULL, 'https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/4.webp', '["https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/1.webp", "https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/2.webp"]', (SELECT id FROM categories WHERE slug = 'kids'), 'kids', 'clothes', 4.5, 198, false, true, '["sweatpants", "casual", "cotton"]'),
('Wool Knit Sweater', 'wool-knit-sweater', 'Cozy wool knit sweater with fun patterns. Keeps kids warm in chilly weather.', 4500, NULL, 'https://cdn.dummyjson.com/product-images/tops/gray-dress/4.webp', '["https://cdn.dummyjson.com/product-images/tops/gray-dress/1.webp", "https://cdn.dummyjson.com/product-images/tops/gray-dress/2.webp"]', (SELECT id FROM categories WHERE slug = 'kids'), 'kids', 'clothes', 4.7, 134, false, true, '["sweater", "wool", "knit"]'),
('Summer Shorts Set', 'summer-shorts-set', 'Cute matching shorts and top set. Bright summer colors kids will love.', 3200, NULL, 'https://cdn.dummyjson.com/product-images/tops/short-frock/4.webp', '["https://cdn.dummyjson.com/product-images/tops/short-frock/1.webp", "https://cdn.dummyjson.com/product-images/tops/short-frock/2.webp"]', (SELECT id FROM categories WHERE slug = 'kids'), 'kids', 'clothes', 4.6, 89, false, true, '["shorts", "set", "summer"]'),
('Hooded Beach Towel Poncho', 'hooded-beach-towel-poncho', 'Fun hooded beach towel poncho. Perfect for swimming days and beach trips.', 2800, NULL, 'https://cdn.dummyjson.com/product-images/tops/tartan-dress/4.webp', '["https://cdn.dummyjson.com/product-images/tops/tartan-dress/1.webp", "https://cdn.dummyjson.com/product-images/tops/tartan-dress/2.webp"]', (SELECT id FROM categories WHERE slug = 'kids'), 'kids', 'clothes', 4.8, 167, false, true, '["poncho", "beach", "hooded"]'),
('Sports Team Jersey', 'sports-team-jersey', 'Stylish sports team jersey for active kids. Breathable mesh fabric.', 3500, NULL, 'https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/3.webp', '["https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/1.webp", "https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/4.webp"]', (SELECT id FROM categories WHERE slug = 'kids'), 'kids', 'clothes', 4.7, 223, false, true, '["jersey", "sports", "athletic"]'),
('Pajama Set', 'pajama-set', 'Cozy two-piece pajama set with fun character prints. Super soft cotton for bedtime.', 2800, NULL, 'https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/4.webp', '["https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/1.webp", "https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/2.webp"]', (SELECT id FROM categories WHERE slug = 'kids'), 'kids', 'clothes', 4.9, 345, false, true, '["pajamas", "sleepwear", "cotton"]'),
('Winter Puffer Jacket', 'winter-puffer-jacket', 'Warm puffer jacket for cold winter days. Lightweight yet incredibly warm.', 6500, 7500, 'https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/4.webp', '["https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/1.webp", "https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/2.webp"]', (SELECT id FROM categories WHERE slug = 'kids'), 'kids', 'clothes', 4.8, 178, true, true, '["jacket", "puffer", "winter"]');
