/*
# Add demographic and product_type columns, seed categories and products

1. New Columns
- `products.demographic` (text) - target demographic: 'men', 'women', 'kids', 'unisex'
- `products.product_type` (text) - product category: 'clothes', 'shoes', 'accessories'

2. Data Changes
- Clear existing categories
- Insert new demographics as categories: Men, Women, Kids
- Insert sample products for each demographic and product type combination

3. Security
- No changes to RLS policies (existing policies allow anon + authenticated SELECT)

4. Notes
- This is a single-tenant storefront with no user accounts
- Categories now represent demographics (Men/Women/Kids)
- Each product has demographic + product_type for granular filtering
- Added indexes for the new columns
- All product images sourced from DummyJSON (https://dummyjson.com)
*/

-- Add demographic and product_type columns to products
ALTER TABLE products ADD COLUMN IF NOT EXISTS demographic text NOT NULL DEFAULT 'unisex';
ALTER TABLE products ADD COLUMN IF NOT EXISTS product_type text NOT NULL DEFAULT 'clothes';

-- Add indexes for new columns
CREATE INDEX IF NOT EXISTS idx_products_demographic ON products(demographic);
CREATE INDEX IF NOT EXISTS idx_products_product_type ON products(product_type);

-- Clear existing categories and products
DELETE FROM products;
DELETE FROM categories;

-- Insert demographic categories (Men, Women, Kids)
INSERT INTO categories (name, slug, description, image_url, sort_order) VALUES
('Men', 'men', 'Discover our curated collection of premium men''s clothing and footwear. Crafted for the modern gentleman.', 'https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/1.webp', 1),
('Women', 'women', 'Explore elegant women''s fashion and footwear. Timeless designs for every occasion.', 'https://cdn.dummyjson.com/product-images/womens-dresses/black-women%27s-gown/1.webp', 2),
('Kids', 'kids', 'Quality clothing and shoes for children. Durable, comfortable, and stylish.', 'https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/1.webp', 3);

-- Insert sample Men's products
INSERT INTO products (name, slug, description, price, compare_at_price, image_url, gallery, category_id, demographic, product_type, rating, review_count, featured, in_stock, tags) VALUES
-- Men's Clothes
('Classic Oxford Shirt', 'classic-oxford-shirt', 'Premium cotton oxford shirt with a timeless fit. Perfect for both casual and formal occasions.', 4500, 5500, 'https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/1.webp', '["https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/2.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/3.webp"]', (SELECT id FROM categories WHERE slug = 'men'), 'men', 'clothes', 4.8, 124, true, true, '["formal", "cotton", "oxford"]'),
('Casual Linen Blazer', 'casual-linen-blazer', 'Lightweight linen blazer perfect for summer events. Relaxed fit with modern tailoring.', 8900, NULL, 'https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/1.webp', '["https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/2.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/3.webp"]', (SELECT id FROM categories WHERE slug = 'men'), 'men', 'clothes', 4.6, 89, true, true, '["blazer", "linen", "summer"]'),
('Slim Fit Chinos', 'slim-fit-chinos', 'Versatile slim-fit chinos in premium stretch cotton. Comfortable for all-day wear.', 5200, NULL, 'https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/1.webp', '["https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/2.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/3.webp"]', (SELECT id FROM categories WHERE slug = 'men'), 'men', 'clothes', 4.5, 156, true, true, '["casual", "chinos", "everyday"]'),
('Merino Wool Sweater', 'merino-wool-sweater', 'Luxuriously soft merino wool sweater. Perfect layering piece for cooler weather.', 7800, 9200, 'https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/1.webp', '["https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/2.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/3.webp"]', (SELECT id FROM categories WHERE slug = 'men'), 'men', 'clothes', 4.9, 203, true, true, '["wool", "sweater", "winter"]'),
('Premium Cotton T-Shirt', 'premium-cotton-tshirt', 'Essential premium cotton t-shirt with a perfect fit. Made from 100% organic cotton.', 2800, NULL, 'https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/1.webp', '["https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/2.webp", "https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/3.webp"]', (SELECT id FROM categories WHERE slug = 'men'), 'men', 'clothes', 4.7, 412, true, true, '["casual", "cotton", "essential"]'),

-- Men's Shoes
('Leather Oxford Shoes', 'leather-oxford-shoes', 'Handcrafted leather oxford shoes. Classic design with exceptional craftsmanship.', 15000, 18000, 'https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/1.webp', '["https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/2.webp", "https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/3.webp"]', (SELECT id FROM categories WHERE slug = 'men'), 'men', 'shoes', 4.9, 87, true, true, '["formal", "leather", "oxford"]'),
('Casual Leather Sneakers', 'casual-leather-sneakers', 'Comfortable leather sneakers perfect for everyday wear. Cushioned insole for all-day comfort.', 8500, NULL, 'https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/1.webp', '["https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/2.webp", "https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/3.webp"]', (SELECT id FROM categories WHERE slug = 'men'), 'men', 'shoes', 4.7, 234, true, true, '["casual", "sneakers", "leather"]'),
('Suede Chelsea Boots', 'suede-chelsea-boots', 'Premium suede chelsea boots with elastic side panels. Stylish and versatile.', 12000, NULL, 'https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/1.webp', '["https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/2.webp", "https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/3.webp"]', (SELECT id FROM categories WHERE slug = 'men'), 'men', 'shoes', 4.6, 156, true, true, '["boots", "suede", "chelsea"]'),
('Running Trainers', 'running-trainers', 'High-performance running trainers with responsive cushioning. Ideal for daily training.', 9800, NULL, 'https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/1.webp', '["https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/2.webp", "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/3.webp"]', (SELECT id FROM categories WHERE slug = 'men'), 'men', 'shoes', 4.8, 198, true, true, '["sports", "running", "trainers"]'),

-- Women's Clothes
('Silk Midi Dress', 'silk-midi-dress', 'Elegant silk midi dress with a flattering silhouette. Perfect for special occasions.', 12500, 15000, 'https://cdn.dummyjson.com/product-images/womens-dresses/black-women%27s-gown/1.webp', '["https://cdn.dummyjson.com/product-images/womens-dresses/black-women%27s-gown/2.webp", "https://cdn.dummyjson.com/product-images/womens-dresses/black-women%27s-gown/3.webp"]', (SELECT id FROM categories WHERE slug = 'women'), 'women', 'clothes', 4.9, 156, true, true, '["dress", "silk", "formal"]'),
('Cashmere Cardigan', 'cashmere-cardigan', 'Luxuriously soft cashmere cardigan. Timeless design for effortless elegance.', 9800, NULL, 'https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/1.webp', '["https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/2.webp", "https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/3.webp"]', (SELECT id FROM categories WHERE slug = 'women'), 'women', 'clothes', 4.8, 234, true, true, '["cardigan", "cashmere", "winter"]'),
('Tailored Wool Trousers', 'tailored-wool-trousers', 'Perfectly tailored wool trousers with a modern fit. Versatile for work or weekend.', 6500, NULL, 'https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/1.webp', '["https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/2.webp", "https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/3.webp"]', (SELECT id FROM categories WHERE slug = 'women'), 'women', 'clothes', 4.7, 189, true, true, '["trousers", "wool", "formal"]'),
('Floral Blouse', 'floral-blouse', 'Delicate floral blouse in premium silk blend. Feminine and sophisticated.', 4200, NULL, 'https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/1.webp', '["https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/2.webp", "https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/3.webp"]', (SELECT id FROM categories WHERE slug = 'women'), 'women', 'clothes', 4.6, 167, true, true, '["blouse", "floral", "silk"]'),
('Linen Summer Dress', 'linen-summer-dress', 'Breezy linen summer dress perfect for warm days. Relaxed fit with beautiful drape.', 5800, NULL, 'https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/1.webp', '["https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/2.webp", "https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/3.webp"]', (SELECT id FROM categories WHERE slug = 'women'), 'women', 'clothes', 4.8, 256, true, true, '["dress", "linen", "summer"]'),

-- Women's Shoes
('Leather Ankle Boots', 'leather-ankle-boots', 'Chic leather ankle boots with block heel. Versatile design for day-to-night wear.', 11000, 13500, 'https://cdn.dummyjson.com/product-images/womens-shoes/black-&-brown-slipper/1.webp', '["https://cdn.dummyjson.com/product-images/womens-shoes/black-&-brown-slipper/2.webp", "https://cdn.dummyjson.com/product-images/womens-shoes/black-&-brown-slipper/3.webp"]', (SELECT id FROM categories WHERE slug = 'women'), 'women', 'shoes', 4.8, 198, true, true, '["boots", "leather", "heel"]'),
('Classic Pumps', 'classic-pumps', 'Timeless patent leather pumps with comfortable heel height. Office-ready elegance.', 9500, NULL, 'https://cdn.dummyjson.com/product-images/womens-shoes/calvin-klein-heel-shoes/1.webp', '["https://cdn.dummyjson.com/product-images/womens-shoes/calvin-klein-heel-shoes/2.webp", "https://cdn.dummyjson.com/product-images/womens-shoes/calvin-klein-heel-shoes/3.webp"]', (SELECT id FROM categories WHERE slug = 'women'), 'women', 'shoes', 4.7, 321, true, true, '["pumps", "formal", "heel"]'),
('Woven Leather Sandals', 'woven-leather-sandals', 'Artisanal woven leather sandals. Handcrafted for exceptional comfort and style.', 6800, NULL, 'https://cdn.dummyjson.com/product-images/womens-shoes/golden-shoes-woman/1.webp', '["https://cdn.dummyjson.com/product-images/womens-shoes/golden-shoes-woman/2.webp", "https://cdn.dummyjson.com/product-images/womens-shoes/golden-shoes-woman/3.webp"]', (SELECT id FROM categories WHERE slug = 'women'), 'women', 'shoes', 4.6, 145, true, true, '["sandals", "leather", "summer"]'),
('Canvas Sneakers', 'canvas-sneakers', 'Comfortable canvas sneakers with vintage-inspired design. Perfect for casual outings.', 4200, NULL, 'https://cdn.dummyjson.com/product-images/womens-shoes/pampi-shoes/1.webp', '["https://cdn.dummyjson.com/product-images/womens-shoes/pampi-shoes/2.webp", "https://cdn.dummyjson.com/product-images/womens-shoes/pampi-shoes/3.webp"]', (SELECT id FROM categories WHERE slug = 'women'), 'women', 'shoes', 4.5, 276, true, true, '["sneakers", "canvas", "casual"]'),

-- Kids' Clothes
('Organic Cotton Romper', 'organic-cotton-romper', 'Soft organic cotton romper for babies. Gentle on delicate skin.', 2800, NULL, 'https://cdn.dummyjson.com/product-images/tops/blue-frock/2.webp', '["https://cdn.dummyjson.com/product-images/tops/blue-frock/1.webp", "https://cdn.dummyjson.com/product-images/tops/blue-frock/3.webp"]', (SELECT id FROM categories WHERE slug = 'kids'), 'kids', 'clothes', 4.9, 89, true, true, '["baby", "organic", "romper"]'),
('Denim Overall Set', 'denim-overall-set', 'Adorable denim overall set for toddlers. Durable and comfortable for play time.', 3500, NULL, 'https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/2.webp', '["https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/1.webp", "https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/3.webp"]', (SELECT id FROM categories WHERE slug = 'kids'), 'kids', 'clothes', 4.7, 156, true, true, '["toddler", "denim", "playwear"]'),
('Kids Cotton Dress', 'kids-cotton-dress', 'Pretty cotton dress with playful print. Perfect for everyday adventures.', 3200, NULL, 'https://cdn.dummyjson.com/product-images/tops/gray-dress/2.webp', '["https://cdn.dummyjson.com/product-images/tops/gray-dress/1.webp", "https://cdn.dummyjson.com/product-images/tops/gray-dress/3.webp"]', (SELECT id FROM categories WHERE slug = 'kids'), 'kids', 'clothes', 4.8, 234, true, true, '["dress", "cotton", "girls"]'),
('Boys Polo Set', 'boys-polo-set', 'Classic polo shirt with matching shorts. Smart casual for special occasions.', 3800, NULL, 'https://cdn.dummyjson.com/product-images/tops/short-frock/2.webp', '["https://cdn.dummyjson.com/product-images/tops/short-frock/1.webp", "https://cdn.dummyjson.com/product-images/tops/short-frock/3.webp"]', (SELECT id FROM categories WHERE slug = 'kids'), 'kids', 'clothes', 4.6, 178, true, true, '["polo", "boys", "smart"]'),
('Fleece Zip Jacket', 'fleece-zip-jacket', 'Cozy fleece zip-up jacket for kids. Perfect for cooler days and outdoor play.', 4500, NULL, 'https://cdn.dummyjson.com/product-images/tops/tartan-dress/2.webp', '["https://cdn.dummyjson.com/product-images/tops/tartan-dress/1.webp", "https://cdn.dummyjson.com/product-images/tops/tartan-dress/3.webp"]', (SELECT id FROM categories WHERE slug = 'kids'), 'kids', 'clothes', 4.7, 201, true, true, '["jacket", "fleece", "warm"]'),

-- Kids' Shoes
('Kids Velcro Sneakers', 'kids-velcro-sneakers', 'Easy-to-wear velcro sneakers for kids. Durable sole for active play.', 3200, NULL, 'https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/1.webp', '["https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/2.webp", "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/3.webp"]', (SELECT id FROM categories WHERE slug = 'kids'), 'kids', 'shoes', 4.8, 189, true, true, '["sneakers", "velcro", "everyday"]'),
('Canvas Slip-On Shoes', 'canvas-slip-on-shoes', 'Convenient slip-on canvas shoes. Lightweight and breathable for summer.', 2800, NULL, 'https://cdn.dummyjson.com/product-images/womens-shoes/red-shoes/1.webp', '["https://cdn.dummyjson.com/product-images/womens-shoes/red-shoes/2.webp", "https://cdn.dummyjson.com/product-images/womens-shoes/red-shoes/3.webp"]', (SELECT id FROM categories WHERE slug = 'kids'), 'kids', 'shoes', 4.7, 167, true, true, '["slip-on", "canvas", "summer"]'),
('Kids Leather Sandals', 'kids-leather-sandals', 'Comfortable leather sandals with adjustable straps. Perfect for growing feet.', 3500, NULL, 'https://cdn.dummyjson.com/product-images/womens-shoes/pampi-shoes/2.webp', '["https://cdn.dummyjson.com/product-images/womens-shoes/pampi-shoes/1.webp", "https://cdn.dummyjson.com/product-images/womens-shoes/pampi-shoes/3.webp"]', (SELECT id FROM categories WHERE slug = 'kids'), 'kids', 'shoes', 4.9, 145, true, true, '["sandals", "leather", "summer"]'),
('School Uniform Shoes', 'school-uniform-shoes', 'Durable school uniform shoes in black leather. Built to last through the school year.', 4800, NULL, 'https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/2.webp', '["https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/1.webp", "https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/3.webp"]', (SELECT id FROM categories WHERE slug = 'kids'), 'kids', 'shoes', 4.6, 234, true, true, '["school", "formal", "leather"]'),
('Sports Trainers', 'sports-trainers', 'Lightweight sports trainers for active kids. Excellent cushioning and support.', 4000, NULL, 'https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/2.webp', '["https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/1.webp", "https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/3.webp"]', (SELECT id FROM categories WHERE slug = 'kids'), 'kids', 'shoes', 4.8, 198, true, true, '["sports", "trainers", "running"]');
